export const DegreeList = [
  { VALUE: 'High School Certificate', ID: 'HS', DISABLED: false },
  { VALUE: 'Secondary School Certificate', ID: 'SSC', DISABLED: false },
  { VALUE: 'Indian Certificate of Secondary Education', ID: 'ICSE', DISABLED: false },
  { VALUE: 'Central Board of Secondary Education (Class 10)', ID: 'CBSE10', DISABLED: false },
  { VALUE: 'Intermediate Certificate', ID: 'Intermediate', DISABLED: false },
  { VALUE: 'Higher Secondary Certificate', ID: 'HSC', DISABLED: false },
  { VALUE: 'Indian School Certificate', ID: 'ISC', DISABLED: false },
  { VALUE: 'Central Board of Secondary Education (Class 12)', ID: 'CBSE12', DISABLED: false },
  { VALUE: "Bachelor's Degree", ID: 'Bachelor', DISABLED: false },
  { VALUE: 'Bachelor of Arts', ID: 'BA', DISABLED: false },
  { VALUE: 'Bachelor of Science', ID: 'BSc', DISABLED: false },
  { VALUE: 'Bachelor of Commerce', ID: 'BCom', DISABLED: false },
  { VALUE: 'Bachelor of Engineering', ID: 'BE', DISABLED: false },
  { VALUE: 'Bachelor of Technology', ID: 'B.Tech', DISABLED: false },
  { VALUE: 'Bachelor of Architecture', ID: 'BArch', DISABLED: false },
  { VALUE: 'Bachelor of Pharmacy', ID: 'BPharm', DISABLED: false },
  { VALUE: 'Bachelor of Business Administration', ID: 'BBA', DISABLED: false },
  { VALUE: 'Bachelor of Computer Applications', ID: 'BCA', DISABLED: false },
  { VALUE: 'Bachelor of Education', ID: 'BEd', DISABLED: false },
  { VALUE: 'Bachelor of Fine Arts', ID: 'BFA', DISABLED: false },
  { VALUE: 'Bachelor of Design', ID: 'BDes', DISABLED: false },
  { VALUE: 'Bachelor of Laws', ID: 'LLB', DISABLED: false },
  { VALUE: 'Bachelor of Medicine, Bachelor of Surgery', ID: 'MBBS', DISABLED: false },
  { VALUE: 'Bachelor of Dental Surgery', ID: 'BDS', DISABLED: false },
  { VALUE: "Master's Degree", ID: 'Master', DISABLED: false },
  { VALUE: 'Master of Arts', ID: 'MA', DISABLED: false },
  { VALUE: 'Master of Science', ID: 'MSc', DISABLED: false },
  { VALUE: 'Master of Commerce', ID: 'MCom', DISABLED: false },
  { VALUE: 'Master of Engineering', ID: 'ME', DISABLED: false },
  { VALUE: 'Master of Technology', ID: 'M.Tech', DISABLED: false },
  { VALUE: 'Master of Architecture', ID: 'MArch', DISABLED: false },
  { VALUE: 'Master of Pharmacy', ID: 'MPharm', DISABLED: false },
  { VALUE: 'Master of Business Administration', ID: 'MBA', DISABLED: false },
  { VALUE: 'Master of Computer Applications', ID: 'MCA', DISABLED: false },
  { VALUE: 'Master of Education', ID: 'MEd', DISABLED: false },
  { VALUE: 'Master of Fine Arts', ID: 'MFA', DISABLED: false },
  { VALUE: 'Master of Design', ID: 'MDes', DISABLED: false },
  { VALUE: 'Master of Laws', ID: 'LLM', DISABLED: false },
  { VALUE: 'Master of Surgery', ID: 'MS', DISABLED: false },
  { VALUE: 'Master of Dental Surgery', ID: 'MDS', DISABLED: false },
  { VALUE: 'Master of Veterinary Science', ID: 'MVSc', DISABLED: false },
  { VALUE: 'Doctor of Philosophy', ID: 'PhD', DISABLED: false },
  { VALUE: 'Doctor of Medicine', ID: 'MD', DISABLED: false },
  { VALUE: 'Doctor of Dental Surgery', ID: 'DDS', DISABLED: false },
  { VALUE: 'Doctor of Education', ID: 'EdD', DISABLED: false },
  { VALUE: 'Doctor of Science', ID: 'DSc', DISABLED: false },
  { VALUE: 'Doctor of Engineering', ID: 'DEng', DISABLED: false },
  { VALUE: 'Diploma in Engineering', ID: 'DiplomaEng', DISABLED: false },
  { VALUE: 'Diploma in Education', ID: 'D.Ed', DISABLED: false },
  { VALUE: 'Diploma in Pharmacy', ID: 'DPharm', DISABLED: false },
  { VALUE: 'Diploma in Hotel Management', ID: 'DHM', DISABLED: false },
  { VALUE: 'Diploma in Journalism and Mass Communication', ID: 'DJMC', DISABLED: false },
  { VALUE: 'Certificate in Information Technology', ID: 'CIT', DISABLED: false },
  { VALUE: 'Certificate in Financial Accounting', ID: 'CFA', DISABLED: false },
  { VALUE: 'Certificate in Digital Marketing', ID: 'CDM', DISABLED: false },
  { VALUE: 'Certificate in Event Management', ID: 'CEM', DISABLED: false },
  { VALUE: 'Chartered Accountancy', ID: 'CA', DISABLED: false },
  { VALUE: 'Company Secretary', ID: 'CS', DISABLED: false },
  { VALUE: 'Cost and Management Accountancy', ID: 'CMA', DISABLED: false },
  { VALUE: 'Fashion Designing', ID: 'FD', DISABLED: false },
  { VALUE: 'Graphic Designing', ID: 'GD', DISABLED: false },
  { VALUE: 'Animation and Multimedia', ID: 'AM', DISABLED: false },
  { VALUE: 'Mass Communication and Journalism', ID: 'MCJ', DISABLED: false },
  { VALUE: 'Hotel Management', ID: 'HM', DISABLED: false }
]

