const JobLayout = {

    "Job ID": {
        SIZE: 6,
        FIELD_TYPE: "Textfield",
        FIELD_LABEL: "Job ID",
        FIELD_ID: "form-field-1",
        FIELD_NAME: "Job ID",
        EXPANDABLE: false,
        REQUIRED: true,
        DISABLED: true,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        ERROR: false,
        VALUE: '',
    },

    "Job Title": {
        SIZE: 12,
        FIELD_TYPE: "Textfield",
        FIELD_LABEL: "Job Title",
        FIELD_ID: "form-field-2",
        FIELD_NAME: "Job Title",
        EXPANDABLE: false,
        REQUIRED: true,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        ERROR: false,
        VALUE: '',
    },

    "Job Locations": {
        FIELD_TYPE: "Job Locations",
        FIELD_LABEL: "Job Locations",
        FIELD_ID: "form-field-3",
        FIELD_NAME: "Job Locations",
        EXPANDABLE: false,
        REQUIRED: true,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        SUB_FIELDS: {

            "Country": {
                SIZE: 6,
                FIELD_TYPE: "Dropdown",
                FIELD_LABEL: "Country",
                FIELD_ID: "form-field-3-a",
                FIELD_NAME: "Country",
                EXPANDABLE: false,
                REQUIRED: true,
                DISABLED: false,
                PARENT_FIELD_NAME: "Job Locations",
                PARENT_FIELD_ID: "form-field-3",
                OPTIONS: [],
                ERROR: false,
                VALUE: '',
            },

            "City": {
                SIZE: 6,
                FIELD_TYPE: "Textfield",
                FIELD_LABEL: "City",
                FIELD_ID: "form-field-3-b",
                FIELD_NAME: "City",
                EXPANDABLE: false,
                REQUIRED: true,
                DISABLED: false,
                PARENT_FIELD_NAME: "Job Locations",
                PARENT_FIELD_ID: "form-field-3",
                ERROR: false,
                VALUE: '',
            },
        },
        ERROR: false,
        VALUE: [],
    },

    "Posting Date": {
        SIZE: 6,
        FIELD_TYPE: "Date",
        FIELD_LABEL: "Posting Date",
        FIELD_ID: "form-field-4",
        FIELD_NAME: "Posting Date",
        EXPANDABLE: false,
        REQUIRED: true,
        DISABLED: true,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        ERROR: false,
        VALUE: '',
    },

    "Application Deadline": {
        SIZE: 6,
        FIELD_TYPE: "Date",
        FIELD_LABEL: "Application Deadline",
        FIELD_ID: "form-field-5",
        FIELD_NAME: "Application Deadline",
        EXPANDABLE: false,
        REQUIRED: true,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        ERROR: false,
        VALUE: '',
    },

    "Employment Type": {
        SIZE: 6,
        FIELD_TYPE: "Dropdown",
        FIELD_LABEL: "Employment Type",
        FIELD_ID: "form-field-6",
        FIELD_NAME: "Employment Type",
        EXPANDABLE: false,
        REQUIRED: false,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        OPTIONS: [
            { VALUE: "Select a option", ID: "Select a option", DISABLED: true },
            { VALUE: "Full-Time", ID: "Full-Time", DISABLED: false },
            { VALUE: "Part-Time", ID: "Part-Time", DISABLED: false },
            { VALUE: "Intern", ID: "Intern", DISABLED: false },
            { VALUE: "Contract", ID: "Contract", DISABLED: false }
        ],
        ERROR: false,
        VALUE: '',
    },

    "Work Mode": {
        SIZE: 6,
        FIELD_TYPE: "Dropdown",
        FIELD_LABEL: "Work Mode",
        FIELD_ID: "form-field-7",
        FIELD_NAME: "Work Mode",
        EXPANDABLE: false,
        REQUIRED: false,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        OPTIONS: [
            { VALUE: "Select a option", ID: "Select a option", DISABLED: true },
            { VALUE: "Remote", ID: "Remote", DISABLED: false },
            { VALUE: "On-site", ID: "On-site", DISABLED: false },
            { VALUE: "Hybrid", ID: "Hybrid", DISABLED: false },
        ],
        ERROR: false,
        VALUE: '',
    },

    "Required Experience": {
        FIELD_TYPE: "Required Experience",
        FIELD_LABEL: "Required Experience",
        FIELD_ID: "form-field-8",
        FIELD_NAME: "Required Experience",
        EXPANDABLE: false,
        REQUIRED: false,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        SUB_FIELDS: {

            "Range Type": {
                SIZE: 5,
                FIELD_TYPE: "Dropdown",
                FIELD_LABEL: "Range Type",
                FIELD_ID: "form-field-8-a",
                FIELD_NAME: "Range Type",
                EXPANDABLE: false,
                REQUIRED: false,
                DISABLED: false,
                PARENT_FIELD_NAME: "Required Experience",
                PARENT_FIELD_ID: "form-field-8",
                OPTIONS: [
                    { VALUE: "Select a option", ID: "Select a option", DISABLED: true },
                    { VALUE: "Minimum", ID: "Minimum", DISABLED: false },
                    { VALUE: "Maximum", ID: "Maximum", DISABLED: false },
                    { VALUE: "Absolute", ID: "Absolute", DISABLED: false },
                ],
                ERROR: false,
                VALUE: '',
            },

            "Range Value": {
                SIZE: 5,
                FIELD_TYPE: "Number",
                FIELD_LABEL: "Range Value",
                FIELD_ID: "form-field-8-b",
                FIELD_NAME: "Range Value",
                EXPANDABLE: false,
                REQUIRED: false,
                DISABLED: false,
                PARENT_FIELD_NAME: "Required Experience",
                PARENT_FIELD_ID: "form-field-8",
                ERROR: false,
                VALUE: '',
            },

            "Unit": {
                SIZE: 2,
                FIELD_TYPE: "Dropdown",
                FIELD_LABEL: "Unit",
                FIELD_ID: "form-field-8-c",
                FIELD_NAME: "Unit",
                EXPANDABLE: false,
                REQUIRED: false,
                DISABLED: false,
                PARENT_FIELD_NAME: "Required Experience",
                PARENT_FIELD_ID: "form-field-8",
                OPTIONS: [
                    { VALUE: "Select a option", ID: "Select a option", DISABLED: true },
                    { VALUE: "Week", ID: "Week", DISABLED: false },
                    { VALUE: "Month", ID: "Month", DISABLED: false },
                    { VALUE: "Year", ID: "Year", DISABLED: false },
                ],
                ERROR: false,
                VALUE: '',
            }
        },
        ERROR: false,
        VALUE: {},
    },

    "Opennings": {
        SIZE: 6,
        FIELD_TYPE: "Number",
        FIELD_LABEL: "Opennings",
        FIELD_ID: "form-field-9",
        FIELD_NAME: "Opennings",
        EXPANDABLE: false,
        REQUIRED: false,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        ERROR: false,
        VALUE: '',
    },

    "Compensation": {
        FIELD_TYPE: "Compensation",
        FIELD_LABEL: "Compensation",
        FIELD_ID: "form-field-10",
        FIELD_NAME: "Compensation",
        EXPANDABLE: false,
        REQUIRED: false,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        SUB_FIELDS: {

            "Range Type": {
                SIZE: 5,
                FIELD_TYPE: "Dropdown",
                FIELD_LABEL: "Range Type",
                FIELD_ID: "form-field-10-a",
                FIELD_NAME: "Range Type",
                EXPANDABLE: false,
                REQUIRED: false,
                DISABLED: false,
                PARENT_FIELD_NAME: "Compensation",
                PARENT_FIELD_ID: "form-field-10",
                OPTIONS: [
                    { VALUE: "Select a option", ID: "Select a option", DISABLED: true },
                    { VALUE: "Minimum", ID: "Minimum", DISABLED: false },
                    { VALUE: "Maximum", ID: "Maximum", DISABLED: false },
                    { VALUE: "Absolute", ID: "Absolute", DISABLED: false },
                ],
                ERROR: false,
                VALUE: '',
            },

            "Range Value": {
                SIZE: 5,
                FIELD_TYPE: "Number",
                FIELD_LABEL: "Range Value",
                FIELD_ID: "form-field-10-b",
                FIELD_NAME: "Range Value",
                EXPANDABLE: false,
                REQUIRED: false,
                DISABLED: false,
                PARENT_FIELD_NAME: "Compensation",
                PARENT_FIELD_ID: "form-field-10",
                ERROR: false,
                VALUE: '',
            },

            "Currency": {
                SIZE: 2,
                FIELD_TYPE: "Dropdown",
                FIELD_LABEL: "Currency",
                FIELD_ID: "form-field-10-c",
                FIELD_NAME: "Currency",
                EXPANDABLE: false,
                REQUIRED: false,
                DISABLED: false,
                PARENT_FIELD_NAME: "Compensation",
                PARENT_FIELD_ID: "form-field-10",
                OPTIONS: [
                    { VALUE: "Select a option", ID: "Select a option", DISABLED: true },
                    { VALUE: "Rupee", ID: "RUPEE", DISABLED: false },
                    { VALUE: "Dollar", ID: "DOLLAR", DISABLED: false },
                    { VALUE: "Euro", ID: "EURO", DISABLED: false },
                    { VALUE: "Yen/Yuan", ID: "YEN/YUAN", DISABLED: false },
                    { VALUE: "Pound", ID: "POUND", DISABLED: false },
                    { VALUE: "Other", ID: "OTHER", DISABLED: false },
                ],
                ERROR: false,
                VALUE: '',
            }
        },
        ERROR: false,
        VALUE: {},
    },

    "Description": {
        FIELD_TYPE: "Description",
        FIELD_LABEL: "Description",
        FIELD_ID: "form-field-11",
        FIELD_NAME: "Description",
        EXPANDABLE: true,
        REQUIRED: false,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        SUB_FIELDS: {

            "Section Name": {
                SIZE: 12,
                FIELD_TYPE: "Textfield",
                FIELD_LABEL: "Section Name",
                FIELD_ID: "form-field-11-a",
                FIELD_NAME: "Section Name",
                EXPANDABLE: false,
                REQUIRED: false,
                DISABLED: false,
                PARENT_FIELD_NAME: "Description",
                PARENT_FIELD_ID: "form-field-11",
                ERROR: false,
                VALUE: '',
            },

            "Content": {
                SIZE: 12,
                FIELD_TYPE: "Textarea",
                FIELD_LABEL: "Content",
                FIELD_ID: "form-field-11-b",
                FIELD_NAME: "Content",
                EXPANDABLE: false,
                REQUIRED: false,
                DISABLED: false,
                PARENT_FIELD_NAME: "Description",
                PARENT_FIELD_ID: "form-field-11",
                ERROR: false,
                VALUE: '',
            }
        },
        ERROR: false,
        VALUE: '',
        CHILDREN: {}
    }
}

export default JobLayout;