const SearchJob = {
    "Search Bar": {
        SIZE: 12,
        FIELD_TYPE: "Textfield",
        FIELD_LABEL: "Search Bar",
        FIELD_ID: "search-field-1",
        FIELD_NAME: "Search Bar",
        PLACEHOLDER: "Try 'Job ID' or 'Keywords' or 'Skills'",
        EXPANDABLE: false,
        REQUIRED: false,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        ERROR: false,
        VALUE: "",
    },
    "Country": {
        SIZE: 3,
        FIELD_TYPE: "Dropdown",
        FIELD_LABLE: "Country",
        FIELD_ID: "search-field-2",
        FIELD_NAME: "Country",
        PLACEHOLDER: "",
        EXPANDABLE: false,
        REQUIRED: false,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        OPTIONS: [],
        ERROR: false,
        VALUE: "",
    },
    "City": {
        SIZE: 3,
        FIELD_TYPE: "Dropdown",
        FIELD_LABLE: "City",
        FIELD_ID: "search-field-3",
        FIELD_NAME: "City",
        PLACEHOLDER: "",
        EXPANDABLE: false,
        REQUIRED: false,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        OPTIONS: [],
        ERROR: false,
        VALUE: "",
    },
    "Experience": {
        SIZE: 3,
        FIELD_TYPE: "Dropdown",
        FIELD_LABLE: "Experience",
        FIELD_ID: "search-field-4",
        FIELD_NAME: "Experience",
        PLACEHOLDER: "",
        EXPANDABLE: false,
        REQUIRED: false,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        OPTIONS: [],
        ERROR: false,
        VALUE: "",
    },
    "Sort By": {
        SIZE: 3,
        FIELD_TYPE: "Dropdown",
        FIELD_LABLE: "Sort By",
        FIELD_ID: "search-field-5",
        FIELD_NAME: "Sort By",
        PLACEHOLDER: "",
        EXPANDABLE: false,
        REQUIRED: false,
        DISABLED: false,
        PARENT_FIELD_NAME: null,
        PARENT_FIELD_ID: null,
        OPTIONS: [
            { VALUE: "Select a option", ID: "Select a option", DISABLED: true },
            { VALUE: "Relevance", ID: "Relevance", DISABLED: false },
            { VALUE: "Older", ID: "Older", DISABLED: false },
            { VALUE: "Newer", ID: "Newer", DISABLED: false }
        ],
        ERROR: false,
        VALUE: "",
    },
};

export default SearchJob;